version: build.{build}
image: Visual Studio 2022

skip_tags: true
skip_commits:
  files:
    - .github/
    - docs/
    - assets/
    - README.md
    - LICENSE
    - CODE_OF_CONDUCT.md
    - CONTRIBUTING.md
    - SECURITY.md

environment:
  github_access_token:
    secure: gtEHCUmmDjYfrp/NEe2qUP+YRnYVMzqvL+5nQi6OIeJwaBoaZWOvVblbx4QnIWz820DkPsSVqHFEU9MELxhsW1h2EC9EEsXb+m5KsA9pzsEUcpllT7Oichb0tKfMmpmD

init:
- cmd: git config --global core.autocrlf true
- cmd: setx IGNORE_NORMALISATION_GIT_HEAD_MOVE 1
- cmd: setx DOTNET_NO_WORKLOAD_UPDATE_NOTIFICATION 1
- cmd: setx DOTNET_CLI_TELEMETRY_OPTOUT 1
- cmd: setx DOTNET_NOLOGO 1
- cmd: RefreshEnv.cmd
- pwsh: Write-Host "Target branch is '$($env:APPVEYOR_REPO_BRANCH)'"

before_build:
- cmd: gitversion /output buildserver /verbosity Minimal
- pwsh: Write-Host "Building Packata version $($env:GitVersion_SemVer)"
- pwsh: |
    . "$env:APPVEYOR_BUILD_FOLDER\github.ps1"
    if (($env:APPVEYOR_REPO_BRANCH -eq "main") -and ($null -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)) {
      $context = [PSCustomObject] @{
        Id = $env:APPVEYOR_REPO_COMMIT
        Owner = ($env:APPVEYOR_REPO_NAME -Split '/')[0]
        Repository = ($env:APPVEYOR_REPO_NAME -Split '/')[1]
        SecretToken = $env:github_access_token
      }
      foreach($id in ($context | Get-Commit-Associated-Pull-Requests)) {
        $context.Id = $id
        $context | Set-Pull-Request-Expected-Labels -Config '.github\conventional_commits_labels.json'
      }
    } else {
        Write-Host 'Not a merge on main built on appveyor. Skipping mapping conventional commits and labels.'
    }

build_script:
  - dotnet build Packata.sln -p:version="%GitVersion_SemVer%" -c Release /p:ContinuousIntegrationBuild=true --nologo 

test_script:
- pwsh: |
    $ErrorActionPreference = "Stop"
    dotnet test src/Packata.Core.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Packata.*.Testing]*" /p:Threshold=10 /p:ThresholdType=line /p:CoverletOutput=../../.coverage/coverage.Packata.Core.xml --test-adapter-path:. --logger:Appveyor --no-build --nologo
    $globalTestResult = $LastExitCode
    dotnet test src/Packata.ResourceReaders.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Packata.*.Testing]*" /p:Threshold=10 /p:ThresholdType=line /p:CoverletOutput=../../.coverage/coverage.Packata.ResourceReaders.xml --test-adapter-path:. --logger:Appveyor --no-build --nologo
    $globalTestResult += $LastExitCode
    dotnet test src/Packata.Provisioners.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Packata.*.Testing]*" /p:Threshold=10 /p:ThresholdType=line /p:CoverletOutput=../../.coverage/coverage.Packata.Provisioners.xml --test-adapter-path:. --logger:Appveyor --no-build --nologo
    $globalTestResult += $LastExitCode
    dotnet test src/Packata.Storages.Testing -c Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Packata.*.Testing]*" /p:Threshold=10 /p:ThresholdType=line /p:CoverletOutput=../../.coverage/coverage.Packata.Storages.xml --test-adapter-path:. --logger:Appveyor --no-build --nologo
    $globalTestResult += $LastExitCode
    if($globalTestResult -ne 0) { $host.SetShouldExit($globalTestResult) }

- pwsh: |
    $ProgressPreference = 'SilentlyContinue'
    Invoke-WebRequest -Uri https://uploader.codecov.io/latest/windows/codecov.exe -Outfile codecov.exe
    .\codecov.exe --dir "./.coverage/"

after_test:
- dotnet pack src/Packata.Core -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo
- dotnet pack src/Packata.ResourceReaders -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo
- dotnet pack src/Packata.Provisioners -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo
- dotnet pack src/Packata.Storages -p:version="%GitVersion_SemVer%" -c Release --include-symbols --no-build --nologo

artifacts:
- path: '**\*.nupkg'
- path: '**\*.snupkg'

deploy:
- provider: NuGet
  api_key:
    secure: Pcfa/EoAxQpHdW+BJIun823nWPWZBTQlTIk76QNSnEIcy/RXxWTAjlHzlfqI2YJT
  skip_symbols: false
  artifact: /.*(\.|\.s)nupkg/
  on:
    branch: main

on_success:
- pwsh: |
    . "$env:APPVEYOR_BUILD_FOLDER\github.ps1"
    if (($env:APPVEYOR_REPO_BRANCH -eq "main") -and ($null -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)) {
        if ($env:GitVersion_Patch -eq '0' -or $env:GitVersion_Patch -eq 0) {
            $context = [PSCustomObject] @{
                Owner = ($env:APPVEYOR_REPO_NAME -Split '/')[0]
                Repository = ($env:APPVEYOR_REPO_NAME -Split '/')[1]
                SecretToken = $env:github_access_token
            }
            if (-not ($context | Check-Release-Published -Tag "v$($env:GitVersion_SemVer)")) {
                $context | Publish-Release `
                    -Tag "v$($env:GitVersion_SemVer)" `
                    -Name "$(($env:APPVEYOR_REPO_NAME -Split '/')[1]) $($env:GitVersion_SemVer)" `
                    -ReleaseNotes `
                    -DiscussionCategory 'Announcements'

                Start-Sleep -Seconds 5
            }
        } else {
            Write-Host "No release published on GitHub when patch is not set to zero."
        }
    } else {
        Write-Host "No release published on GitHub when not on branch main."
    }
