<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>NDJSON resource reader provider for Packata.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Packata.ResourceReaders\Packata.ResourceReaders.csproj" />
    <PackageReference Include="PocketCsvReader.Ndjson" Version="2.42.1" />
  </ItemGroup>
</Project>
